dist: focal

before_install:
  - gem install package_cloud

script:
  - sudo ./travis-build.sh
  - package_cloud push nitrux/testing/debian/trixie *.deb

branches:
  only:
    - legacy

notifications:
  email: false
  
